apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: argocd project
  destinations:
    # shared-services
  - namespace: argocd
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: argoproj.io
    kind: ApplicationSet
  - group: argoproj.io
    kind: AppProject
  - group: argoproj.io
    kind: Application  
  sourceRepos:
  - https://github.com/Anveshvadi/Argocd.git
