apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiobase
  namespace: argocd
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.21.5
    helm:
      releaseName: istiobase
      values: |
        base:
          enableCRDTemplates: true
          enableIstioConfigCRDs: true   # For istioctl usage to disable istio config CRDs in base
        defaultRevision: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
