apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-agent
  namespace: argocd
  labels:
    app: elastic-agent
spec:
  replicas: 4
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      containers:
      - name: elastic-agent
        image: pavansa/notes-app
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-agent
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-services-application-set
  source:
    path: components/project-configuration
    repoURL: https://github.com/Anveshvadi/Argocd.git
    targetRevision: main

