apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-agent
  labels:
    app: elastic-agent
spec:
  replicas: 4
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      containers:
      - name: elastic-agent
        image: pavansa/notes-app
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
